### ISSUE TITLE
Blog pages links and meta

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/cpal-site#11]
@hoshmn there is now a 2nd blog post [here](https://dallasisd.resourceexplorer.org/operation-connectivity/). I don't know how to make it link from the /in-action page, however, with the way it's set up (the "read post" button goes nowhere). 

Would be good to make this the 2nd blog post on the homepage as well.

Maybe can be wrapped in with work to nest these blog posts under /in-action? Thanks!

**Comment by hoshmn** [comment]
done!
