### ISSUE TITLE
Add user info submission form

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/cpal-site#3]
Specs:

- User can enter their email address and "submit" via a "band" present on every site page (just above footer)
- Pressing submit takes user to another page, `/signup`
- This page has a form allowing additional info to be submitted, or user can press a button to complete the form
- The email address entered in the first step is carried forward to the `signup` page

The form code that routes the info to the client's database is supplied in a file on a separate branch.

**Signup page content:**

### Almost done!
We'd love to know more about you. You can enter additional info below, or **click here** [same function as "submit" button below] to finish and submit only your email address.

First name [ .......] Last name [ ....... ]
Email address [auto-filled]
Organization [ the id and name for this field should be "company" to work with the database, but we can label it "organization" on the front end ]
Neighborhood [ ...... ]
SUBMIT (button)

Submission of form will direct user to `/thankyou` page.

"Thank you" page content:

Thanks for submitting your info!

(Then can we either a) redirect them to the page they started from with the message "redirecting in x seconds to ...'; b) redirect to homepage; or c) give them a button to take them back to the homepage?)

**Comment by hoshmn** [comment]
@james-minton first draft in. Very basic styling of form, leaves much to be desired... but works. Currently redirects directly back to home. Can do the /thankyou route with a link home, but will take a bit more time (especially to apply _any_ styles), going to focus on other things for now

**Comment by hoshmn** [comment]
if you want to tinker with it, you can set DEBUG => true (and change the debugEmail)

**Comment by hoshmn** [comment]
Also I noticed the FAQ `How can I stay informed about updates to the CRE?` - I can route here, and maybe change the top text for users who land here without an email entered. could just be the signup band text, "Subscribe to our e-mail updates"

**Comment by james-minton** [comment]
@hoshmn ah gotcha, I'd imagined it at first as being just a scroll-down link to the signup area on the page, but I think your idea is better?

**Comment by hoshmn** [comment]
hmm yeah, that could work too. one more click, but everyone loves an auto-scroll :)
