### ISSUE TITLE
Add contact form

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/cpal-site#5]
Structure:

### To get in touch, please select the reason for contacting us (required):

[select menu: contains a list of options (forthcoming). Selecting certain of the options triggers a panel like the following*:]

Is your question answered below? (Click each question to view answer).

[FAQ items related to user's selection appear here (as well as the contact form, which has been hidden until now). This is to head off emails that may be answered by FAQs.]

If the above does not answer your question, please use the form below:

[name] (required)
[your email address] (required)
[subject] (required)
[textarea for message] (required)

[SUBMIT]

* if user's reason for contacting is not in the list, they can choose "other" and just have the contact form appear.

**Comment by james-minton** [comment]
Here are the **select menu** options (and what the page should do in response to each selection):

I am reaching out because:
- I have questions about why (and by whom) the Community Resource Explorer was built, who funds it, etc.
    - display FAQs from the “background” section below this menu
- I have questions about the data: how it was calculated, where it came from, which schools are included, etc.
    - display FAQs from the “about the data” section
- The data does not match my personal experience
    - Display FAQ item: “The data for my neighborhood doesn’t match my personal experience. Why might that be?”
- I’d like to stay informed about the Resource Explorer
    - FAQ item: “How can I stay informed about updates to the CRE?”
- I’d like to share insights about my neighborhood to help improve the Resource Explorer
    - FAQ item: “I have insight about my neighborhood that I would like to share. How can I do that?”
- I am interested in applying the Resource Explorer to schools outside of Dallas ISD. Whom should I talk to?
    - FAQ item: “I am interested in the CRE for schools outside of Dallas ISD. Who should I talk to?”
- I need help with using the website or something’s not working
    - This creates a form that routes to us instead of CPAL. I will set these forms up in Netlify and share the code to incorporate soon.
- Another reason
    - Skips FAQ items, just goes to the regular form

Note that per the above, **there will need to be 2 forms:** one for submissions to CPAL (which should appear for all the selections but one), and one that routes to us (for site usability/troubleshooting questions). Will set those up and share the form id's with you.

**Comment by hoshmn** [comment]
basic form implemented. might want to test it's submitting correctly. I'll let you close if sufficient @james-minton
