### ISSUE TITLE
Add "Get the Data" table

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/cpal-site#6]
A simple bare-bones just-the-facts page would be all we need, leveraging existing heading and paragraph styles.
Will need to allow client the ability to edit this table and upload files via the CMS.

Page url should be `/get-the-data`.

[Specs are here](https://docs.google.com/document/d/1m9W58O5vOw82tRhw1Yc69ric8U-7SlEhSM1sqL_vcRU/edit?usp=sharing).

**Comment by james-minton** [comment]
@hoshmn Wanted to update you on how CSV / R files will be hosted: client will provide dropbox links for the table. Will let you know when those are in.

**Comment by hoshmn** [comment]
basic version up
